Batch Creation and Deletion of Waypoints
ubcuas/GCOM-2023 pull request #8
Opened 2023-12-02 21:36 UTC by jimgeng

Batch creation and deletion of waypoints now exposed as `POST` and `DEL` endpoints for the `/waypoints` route, with corresponding updated swagger documentation.

Preliminary testing (in Insomnia) has been done to ensure basic functionality, further edge-case tests probably should be done to ensure code strength.

Other small changes:
- capitalization of response messages is more consistent.
- changed server start address to include the `localhost` keyword (without this my firewall acts up, no functional difference with or without otherwise).

2023-12-02 22:06 UTC, 21chanas3 requested changes
Change batch deletion behavior and eliminate intermediate struct used in JSON parsing

2023-12-02 22:06 UTC, 21chanas3 commented on controllers/waypoint_controller.go
> +		dbAction := db.Delete(&models.Waypoint{}, curID)
Ideally, we should check that all of the IDs actually do exist before running any delete operation to avoid partial deletion

2023-12-02 22:06 UTC, 21chanas3 commented on models/waypoint_model.go
> +	IDs []string `json:"ids" example:"1,2,3"`
As per your comment creating a struct here is not necessary. A good resource is this: https://pkg.go.dev/encoding/json?utm_source=godoc#Unmarshal

The JSON format should just be a simple JSON integer array, i.e. [1, 2, 3, 4]

2023-12-02 22:06 UTC, 21chanas3 commented on main.go
> +	e.Logger.Fatal(e.Start("localhost:1323"))
Did you encounter errors without "localhost"?

2023-12-02 23:45 UTC, jimgeng commented on main.go
> +	e.Logger.Fatal(e.Start("localhost:1323"))
Windows pops up with a firewall whitelist dialog, running `go run main.go` without `localhost` keyword runs a temp executable in the windows temp folder, and the firewall pops up with a whitelist dialog without localhost.
![image](https://github.com/ubcuas/GCOM-2023/assets/42251403/118fccef-4cfa-4e8a-968a-ac911ee2de02)

2024-01-13 21:16 UTC, 21chanas3 approved these changes
lgtm

2024-01-13 21:16 UTC, merged